SELECT S.PROJECT, COUNT(SA.SAMPLE_ID) AS NumberOfSamples, ISNULL(R.LAB_ELEMENT, 'N/A') AS ChemicalElement, 
CAST(ISNULL(MIN(R.RESULT), 0) AS DECIMAL(10, 2)) AS Minimum, 
CAST(ISNULL(MAX(R.RESULT), 0) AS DECIMAL(10, 2)) AS Maximum,
CAST(ISNULL(AVG(R.RESULT), 0) AS DECIMAL(10, 2)) AS Average, 
CAST(ISNULL(STDEV(R.RESULT), '0') AS DECIMAL(10, 2)) AS StandardDeviation 
FROM GB_SITE AS S
  LEFT JOIN GB_SAMPLE AS SA ON S.SITE_ID = SA.SITE_ID
  LEFT JOIN ST_DESPATCH_SAMPLE DS ON SA.SAMPLE_ID = DS.SAMPLE_ID
  LEFT JOIN ST_RESULT AS R ON DS.SAMPLE_TAG = R.SAMPLE_TAG
GROUP BY S.PROJECT, R.LAB_ELEMENT
ORDER BY S.PROJECT